"""
AI Agent Orchestration Service.

Implements:
  - Agent registry and lifecycle
  - Planner: decide which agent should handle an event
  - Executor: run an agent action
  - Short-term (in-memory) + long-term (DB) memory
  - Multi-agent coordination via event bus
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Callable, Coroutine, Dict, List, Optional

from sqlalchemy.ext.asyncio import AsyncSession

from backend.core.events import Event, Topics, get_event_bus
from backend.models.alert import AlertCategory, AlertCreate, AlertSeverity
from backend.models.work_order import WOPriority, WOType, WorkOrderCreate

logger = logging.getLogger(__name__)


# ── Agent memory ───────────────────────────────────────────────────────────────
@dataclass
class AgentMemory:
    """Short-term in-process memory per agent session."""
    agent_id: str
    entries:  List[Dict[str, Any]] = field(default_factory=list)
    max_entries: int = 200

    def remember(self, key: str, value: Any) -> None:
        self.entries.append({"key": key, "value": value, "ts": datetime.now(tz=timezone.utc).isoformat()})
        if len(self.entries) > self.max_entries:
            self.entries = self.entries[-self.max_entries:]

    def recall(self, key: str) -> Optional[Any]:
        for entry in reversed(self.entries):
            if entry["key"] == key:
                return entry["value"]
        return None


# ── Agent action log ───────────────────────────────────────────────────────────
@dataclass
class AgentActionRecord:
    action_id:  str = field(default_factory=lambda: str(uuid.uuid4()))
    agent_id:   str = ""
    action:     str = ""
    payload:    Dict[str, Any] = field(default_factory=dict)
    result:     Optional[Any] = None
    success:    bool = False
    error:      Optional[str] = None
    executed_at: datetime = field(default_factory=lambda: datetime.now(tz=timezone.utc))


# Global action log (production: persist to DB)
_action_log: List[AgentActionRecord] = []


def get_action_log(limit: int = 100) -> List[AgentActionRecord]:
    return _action_log[-limit:]


# ── Base agent ─────────────────────────────────────────────────────────────────
class BaseAgent:
    def __init__(self, agent_id: str, name: str, role: str):
        self.agent_id = agent_id
        self.name = name
        self.role = role
        self.memory = AgentMemory(agent_id=agent_id)
        self.enabled = True

    async def handle_event(self, event: Event, db: AsyncSession) -> Optional[Dict[str, Any]]:
        raise NotImplementedError

    def _record(self, action: str, payload: dict, result: Any, success: bool, error: Optional[str] = None):
        rec = AgentActionRecord(
            agent_id=self.agent_id, action=action, payload=payload,
            result=result, success=success, error=error,
        )
        _action_log.append(rec)
        if len(_action_log) > 2000:
            _action_log.pop(0)
        return rec


# ── Maintenance Agent ─────────────────────────────────────────────────────────
class MaintenanceAgent(BaseAgent):
    def __init__(self):
        super().__init__("maintenance_agent", "Maintenance Agent", "maintenance")

    async def handle_event(self, event: Event, db: AsyncSession) -> Optional[Dict[str, Any]]:
        if event.topic == Topics.MACHINE_ALERT_TRIGGERED:
            return await self._respond_to_alert(event, db)
        if event.topic == Topics.ANOMALY_DETECTED:
            return await self._schedule_inspection(event, db)
        return None

    async def _respond_to_alert(self, event: Event, db: AsyncSession) -> dict:
        from backend.services.cmms_service import create_work_order
        payload = event.payload
        severity = payload.get("severity", "warning")
        priority = WOPriority.CRITICAL if severity == "critical" else WOPriority.HIGH

        # Check memory: don't create duplicate WO for same asset in same session
        asset_id = payload.get("asset_id")
        last_wo = self.memory.recall(f"last_wo_{asset_id}")
        if last_wo:
            logger.info("MaintenanceAgent: WO already created for asset %s recently", asset_id)
            return {"skipped": True, "reason": "duplicate_prevention", "last_wo": last_wo}

        try:
            wo = await create_work_order(
                db,
                WorkOrderCreate(
                    company_id=payload["company_id"],
                    asset_id=asset_id,
                    title=f"[Agent] Maintenance response: {payload.get('title', 'Alert')}",
                    description=f"Auto-generated by MaintenanceAgent in response to alert {payload.get('alert_id')}",
                    wo_type=WOType.CORRECTIVE,
                    priority=priority,
                    alert_id=payload.get("alert_id"),
                ),
                created_by=self.agent_id,
            )
            self.memory.remember(f"last_wo_{asset_id}", wo.id)
            bus = get_event_bus()
            await bus.publish(Topics.AGENT_ACTION_EXECUTED, {
                "agent": self.name, "action": "create_work_order", "work_order_id": wo.id
            }, source=self.agent_id)
            self._record("create_work_order", payload, wo.id, True)
            return {"work_order_id": wo.id, "wo_number": wo.wo_number}
        except Exception as exc:
            self._record("create_work_order", payload, None, False, str(exc))
            raise

    async def _schedule_inspection(self, event: Event, db: AsyncSession) -> dict:
        from backend.services.cmms_service import create_work_order
        payload = event.payload
        try:
            wo = await create_work_order(
                db,
                WorkOrderCreate(
                    company_id=payload["company_id"],
                    asset_id=payload.get("asset_id"),
                    title=f"[Agent] Predictive inspection — {payload.get('metric', 'anomaly')}",
                    wo_type=WOType.PREDICTIVE,
                    priority=WOPriority.MEDIUM,
                ),
                created_by=self.agent_id,
            )
            self._record("schedule_inspection", payload, wo.id, True)
            return {"work_order_id": wo.id}
        except Exception as exc:
            self._record("schedule_inspection", payload, None, False, str(exc))
            raise


# ── Optimization Agent ────────────────────────────────────────────────────────
class OptimizationAgent(BaseAgent):
    def __init__(self):
        super().__init__("optimization_agent", "Optimization Agent", "optimization")

    async def handle_event(self, event: Event, db: AsyncSession) -> Optional[Dict[str, Any]]:
        if event.topic == Topics.ENERGY_THRESHOLD_EXCEEDED:
            return await self._recommend_energy_action(event, db)
        return None

    async def _recommend_energy_action(self, event: Event, db: AsyncSession) -> dict:
        payload = event.payload
        recommendation = {
            "agent": self.name,
            "action": "energy_optimization_recommendation",
            "company_id": payload.get("company_id"),
            "asset_id":   payload.get("asset_id"),
            "recommendation": (
                f"Energy consumption {payload.get('current_kwh', '?')} kWh exceeds target "
                f"{payload.get('target_kwh', '?')} kWh. "
                "Suggested actions: shift load to off-peak hours, inspect motor efficiency, "
                "evaluate variable-frequency drive (VFD) installation."
            ),
            "potential_saving_pct": 15.0,
        }
        self._record("energy_recommendation", payload, recommendation, True)
        return recommendation


# ── Commercial Agent ──────────────────────────────────────────────────────────
class CommercialAgent(BaseAgent):
    def __init__(self):
        super().__init__("commercial_agent", "Commercial Agent", "commercial")

    async def handle_event(self, event: Event, db: AsyncSession) -> Optional[Dict[str, Any]]:
        if event.topic == Topics.UPSELL_OPPORTUNITY:
            return await self._generate_offer(event, db)
        if event.topic == Topics.WORK_ORDER_CREATED:
            return await self._check_upsell_trigger(event, db)
        return None

    async def _generate_offer(self, event: Event, db: AsyncSession) -> dict:
        payload = event.payload
        offer = {
            "agent": self.name,
            "offer_type": payload.get("offer_type", "upgrade"),
            "company_id": payload.get("company_id"),
            "asset_id":   payload.get("asset_id"),
            "title": payload.get("title", "Upgrade opportunity"),
            "trigger": payload.get("trigger", "when upgrades are needed"),
            "estimated_value_usd": payload.get("estimated_value", 0),
        }
        self._record("generate_offer", payload, offer, True)
        logger.info("CommercialAgent: generated offer for company %s", payload.get("company_id"))
        return offer

    async def _check_upsell_trigger(self, event: Event, db: AsyncSession) -> Optional[dict]:
        payload = event.payload
        # If a corrective WO was just created, check if a predictive upgrade upsell applies
        if payload.get("priority") in ("critical", "high"):
            bus = get_event_bus()
            await bus.publish(Topics.UPSELL_OPPORTUNITY, {
                "company_id":  payload.get("company_id"),
                "asset_id":    payload.get("asset_id"),
                "offer_type":  "predictive_maintenance_upgrade",
                "title":       "Upgrade to Predictive Maintenance subscription",
                "trigger":     "when upgrades are needed",
                "estimated_value": 12000,
            }, source=self.agent_id)
        return None


# ── Orchestrator ───────────────────────────────────────────────────────────────
class AgentOrchestrator:
    """Routes events to the correct agent(s) and coordinates responses."""

    PRIORITY_ORDER = ["maintenance_agent", "optimization_agent", "commercial_agent"]

    def __init__(self):
        self._agents: Dict[str, BaseAgent] = {}
        self._topic_map: Dict[str, List[str]] = {
            Topics.MACHINE_ALERT_TRIGGERED:   ["maintenance_agent", "commercial_agent"],
            Topics.ANOMALY_DETECTED:          ["maintenance_agent"],
            Topics.ENERGY_THRESHOLD_EXCEEDED: ["optimization_agent"],
            Topics.UPSELL_OPPORTUNITY:        ["commercial_agent"],
            Topics.WORK_ORDER_CREATED:        ["commercial_agent"],
        }

    def register(self, agent: BaseAgent) -> None:
        self._agents[agent.agent_id] = agent
        logger.info("Registered agent: %s (%s)", agent.name, agent.agent_id)

    async def route(self, event: Event, db: AsyncSession) -> List[Dict[str, Any]]:
        agent_ids = self._topic_map.get(event.topic, [])
        results = []
        for agent_id in agent_ids:
            agent = self._agents.get(agent_id)
            if agent and agent.enabled:
                try:
                    result = await agent.handle_event(event, db)
                    if result:
                        results.append({"agent_id": agent_id, "result": result})
                except Exception as exc:
                    logger.error("Agent %s failed on event %s: %s", agent_id, event.topic, exc)
        return results

    def list_agents(self) -> List[dict]:
        return [
            {
                "agent_id": a.agent_id,
                "name": a.name,
                "role": a.role,
                "enabled": a.enabled,
            }
            for a in self._agents.values()
        ]


# ── Singleton orchestrator ────────────────────────────────────────────────────
_orchestrator: Optional[AgentOrchestrator] = None


def get_orchestrator() -> AgentOrchestrator:
    global _orchestrator
    if _orchestrator is None:
        _orchestrator = AgentOrchestrator()
        _orchestrator.register(MaintenanceAgent())
        _orchestrator.register(OptimizationAgent())
        _orchestrator.register(CommercialAgent())

        # Wire agents into event bus
        bus = get_event_bus()

        async def _dispatch(event: Event) -> None:
            # We can't inject DB here (no request context); agents that need DB
            # will use a dedicated session from the service layer.
            logger.debug("Orchestrator dispatching event: %s", event.topic)

        for topic in [
            Topics.MACHINE_ALERT_TRIGGERED,
            Topics.ANOMALY_DETECTED,
            Topics.ENERGY_THRESHOLD_EXCEEDED,
            Topics.UPSELL_OPPORTUNITY,
            Topics.WORK_ORDER_CREATED,
        ]:
            bus.subscribe(topic, _dispatch)

    return _orchestrator


async def run_agent_action(
    db: AsyncSession,
    agent_id: str,
    action: str,
    payload: Dict[str, Any],
) -> Dict[str, Any]:
    """Imperatively invoke an agent action (e.g. from an API endpoint)."""
    orch = get_orchestrator()
    agents = {a["agent_id"]: a for a in orch.list_agents()}
    if agent_id not in agents:
        raise ValueError(f"Unknown agent: {agent_id}")

    event = Event(topic=f"agent.direct.{action}", payload=payload, source="api")
    results = await orch.route(event, db)
    return {"agent_id": agent_id, "action": action, "results": results}
